export const API_URL = {
  authorization: '/api/auth/',
  listOfDatabases: '/api/db/',
  listOfUsers: '/api/db/users/',
  userDatabases: '/api/db/users/{user}/',
  userProfile: '/api/db/users/{user}/profile',
  deleteUserDatabase: '/api/db/users/{user}/{database}',
  tableMetadataForUser: '/api/db/users/{user}/{database}/{table}',
  tableDataForUser: '/api/db/users/{user}/{database}/{table}/full',
  tablePageAndCountForUser: '/api/db/users/{user}/{database}/{table}/pages/count',
  tablePageMetadateForUser: '/api/db/users/{user}/{database}/{table}/pages/{page}',
  tablePageDataForUser: '/api/db/users/{user}/{database}/{table}/pages/{page}/full',
  tableMetadataForMe: '/api/db/{database}/{table}',
  tableDataForMe: '/api/db/{database}/{table}/full',
  tablePageAndCountForMe: '/api/db/{database}/{table}/pages/count',
  tablePageMetadateForMe: '/api/db/users/{database}/{table}/pages/{page}',
  tablePageDataForMe: '/api/db/{database}/{table}/pages/{page}/full',
  tableDataRecord: '/api/db/{database}/{table}/{record}',
  additives: '/api/jobs/additives/',
  magic: '/api/jobs/magic',
  models: '/api/jobs/models/',
  createTask: '/api/jobs/create/{_type}',
};

